name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup NodeJS"
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: "Install NPM dependencies"
      run: npm install

    - name: "Install CLI tools"
      run: "npm install --global @gridsome/cli purgecss"

    - name: "Build"
      run: npm run build

    - name: "PurgeCSS pass"
      run: purgecss --config purgecss.config.js --output dist/assets/css/

    - name: "Deploy"
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
        publish_branch: master
        external_repository: Ryujinx/ryujinx.github.io 
        user_name: GitHub Action
        user_email: action@github.com
        force_orphan: true
